%% Load part
% parameters
load parameters.mat
load epipolar_line_parameters.mat

% Load last frame information
last_camera_image = imread([main_file_path, cam_img_file_path, ...
    cam_img_file_name, '1', cam_file_suffix]);
last_camera_image = double(last_camera_image) / 255.0;
last_x_gt = load([main_file_path, pro_x_file_path, ...
    pro_x_file_name, '1', file_suffix]);
last_y_gt = load([main_file_path, pro_y_file_path, ...
    pro_y_file_name, '1', file_suffix]);


for h = viewportMatrix(2, 1):viewportMatrix(2, 2)
    for w = viewportMatrix(1, 1):viewportMatrix(1, 2)
        if (last_x_gt(h, w) <= 0)
            last_x_gt(h, w) = (last_x_gt(h-1, w) + last_x_gt(h+1, w)) / 2;
        end
    end
end
[last_depth_mat, last_valid_mask] = FillDepthMat(last_x_gt, ...
    last_y_gt, ...
    viewportMatrix);

%% Iteration part
for frame_idx = 2:2
    % Load now frame information
    now_camera_image = imread([main_file_path, cam_img_file_path, ...
        cam_img_file_name, num2str(frame_idx), cam_file_suffix]);
    now_camera_image = double(now_camera_image) / 255.0;
    % now_camera_image = NormalizeCameraImage(now_camera_image, viewportMatrix);
    now_x_gt = load([main_file_path, pro_x_file_path, ...
        pro_x_file_name, num2str(frame_idx), file_suffix]);
    now_y_gt = load([main_file_path, pro_y_file_path, ...
        pro_y_file_name, num2str(frame_idx), file_suffix]);

    for h = viewportMatrix(2, 1):viewportMatrix(2, 2)
        for w = viewportMatrix(1, 1):viewportMatrix(1, 2)
            if (now_x_gt(h, w) <= 0)
                now_x_gt(h, w) = (now_x_gt(h-1, w) + now_x_gt(h+1, w)) / 2;
            end
        end
    end
    [now_depth_mat, now_valid_mask] = FillDepthMat(now_x_gt, ...
        now_y_gt, ...
        viewportMatrix);
    

    %% BeliefField
    % Generate Q field and initialize it
    % cameraImageNorm = NormalizeCameraImage(now_camera_image, viewportMatrix);
    beliefField = FillInitialBeliefField(now_camera_image, ...
        pattern, ...
        last_depth_mat, ...
        now_depth_mat, ...
        lineA, ...
        lineB, ...
        lineC, ...
        viewportMatrix, ...
        norm_sigma_u, ...
        voxelSize, ...
        halfVoxelRange);
    save(['beliefField', num2str(0), '.mat'], 'beliefField');
    depthMap = debugGetDepthFromBeliefField(beliefField, ...
            last_depth_mat, ...
            viewportMatrix, ...
            voxelSize, ...
            halfVoxelRange);
     writepointcloud(depthMap, camMat, ...
            ['point_cloud/frame2_iter', num2str(0), '.txt'], ...
            viewportMatrix);
    fprintf('%d: initialized.\n', frame_idx);
    
    % Iteration
    for i_idx = 1:10
        beliefField = BeliefFieldIterationFast(beliefField, ...
            now_camera_image, ...
            pattern, ...
            last_depth_mat, ...
            now_depth_mat, ...
            lineA, ...
            lineB, ...
            lineC, ...
            norm_sigma_u, ...
            norm_sigma_p, ...
            viewportMatrix, ...
            voxelSize, ...
            halfVoxelRange, ...
            halfNeighborRange);
        save(['beliefField', num2str(i_idx), '.mat'], 'beliefField');
        depthMap = debugGetDepthFromBeliefField(beliefField, ...
            last_depth_mat, ...
            viewportMatrix, ...
            voxelSize, ...
            halfVoxelRange);
        writepointcloud(depthMap, camMat, ...
            ['point_cloud/frame2_iter', num2str(i_idx), '.txt'], ...
            viewportMatrix);
        fprintf(' %d_%d: iteration.\n', frame_idx, i_idx);
    end
end
