last_x_mat_vp = last_x_gt(viewportMatrix(2,1):viewportMatrix(2,2), ...
    viewportMatrix(1,1):viewportMatrix(1,2));
last_y_mat_vp = last_y_gt(viewportMatrix(2,1):viewportMatrix(2,2), ...
    viewportMatrix(1,1):viewportMatrix(1,2));

now_x_mat_vp = now_x_gt(viewportMatrix(2,1):viewportMatrix(2,2), ...
    viewportMatrix(1,1):viewportMatrix(1,2));
now_y_mat_vp = now_y_gt(viewportMatrix(2,1):viewportMatrix(2,2), ...
    viewportMatrix(1,1):viewportMatrix(1,2));


camera_vp = now_camera_image(viewportMatrix(2,1):viewportMatrix(2,2), ...
    viewportMatrix(1,1):viewportMatrix(1,2));
pattern_vp = pattern(370:508, 748:884);