clc;clear;close all
%打开图像
I=imread('lena.bmp');
%定义运动30像素，角度为45度
Len=30;
Theta=45;
PSF=fspecial('motion',Len,Theta);
Blurredmotion=imfilter(I,PSF,'circular','conv');
%采用真实的PSF复原图像
WnrI1=deconvwnr(Blurredmotion,PSF);
%采用1.5倍于真实模糊距离的PSF复原图像
WnrI2=deconvwnr(Blurredmotion,fspecial('motion',1.5*Len,Theta));
%采用1.5倍于真实运动角度的PSF复原图像
WnrI3=deconvwnr(Blurredmotion,fspecial('motion',Len,1.5*Theta));
subplot(2,3,1);
imshow(I);
title('原始图像');
subplot(2,3,2);
imshow(Blurredmotion);
title('运动模糊图像');
subplot(2,3,3);
imshow(WnrI1);
title('采用真实PSF复原图像');
subplot(2,3,4);
imshow(WnrI2);
title('采用1.5倍于真实模糊距离的PSF复原图像');
subplot(2,3,6);
imshow(WnrI3);
title('采用1.5倍于真实运动角度的PSF复原图像');

