function value = Phi_p_v(delta_depth, ...
    norm_sigma, ...
    c_xy, ...
    p_xy, ...
    v_delta_depth)

    norm_value = (delta_depth - v_delta_depth)^2 / (s*norm_sigma^2);

    value = norm_value;
end
