% Get depth map
depthMap = debugGetDepthFromBeliefField(beliefField, ...
    last_depth_mat, ...
    viewportMatrix, ...
    voxelSize, ...
    halfVoxelRange);
showMap = depth2showmat(depthMap, camMat, viewportMatrix);
figure(1),imshow(depthMap(viewportMatrix(2,1)+10:viewportMatrix(2,2)-10, ...
    viewportMatrix(1,1)+10:viewportMatrix(1,2)-10), []);
figure(2),imshow(now_camera_image(viewportMatrix(2,1):viewportMatrix(2,2), ...
    viewportMatrix(1,1):viewportMatrix(1,2)));
figure(3), imshow(showMap(viewportMatrix(2,1)+10:viewportMatrix(2,2)-10, ...
    viewportMatrix(1,1)+10:viewportMatrix(1,2)-10), []);