function CreateTab(htab,evdt,hpanel,hstatus)
for i=1:length(hpanel)
    uicontrol('Parent',hpanel(i),...
        'Units','normalized',...
        'Position',[0.3,0.5,0.2,0.1],...
        'BackgroundColor',[1,1,1],...
        'ForegroundColor',[rand,rand,rand],...
        'FontSize',20,...
        'Style','text',...
        'String',['Tab',num2str(i)]);
end
