%% Load part
% parameters
load parameters.mat
load epipolar_line_parameters.mat

%% Load All Information
camera_image = cell(5, 1);
xpro_mats = cell(5, 1);
ypro_mats = cell(5, 1);
depth_mats = cell(5, 1);
valid_mats = cell(5, 1);
for i = 1:5
    camera_image{i, 1} = imread([main_file_path, cam_img_file_path, ...
        cam_img_file_name, num2str(i), cam_file_suffix]);
    camera_image{i, 1} = double(camera_image{i, 1}) / 255.0;
    xpro_mats{i, 1} = load([main_file_path, pro_x_file_path, ...
        pro_x_file_name, num2str(i), file_suffix]);
    ypro_mats{i, 1} = load([main_file_path, pro_y_file_path, ...
        pro_y_file_name, num2str(i), file_suffix]);

    xpro_mats{i, 1} = HoleFilling(xpro_mats{i, 1}, 2, viewportMatrix);
    ypro_mats{i, 1} = HoleFilling(ypro_mats{i, 1}, 2, viewportMatrix);

    [depth_mats{i, 1}, valid_mats{i, 1}] = FillDepthMat(xpro_mats{i, 1}, ...
        ypro_mats{i, 1}, viewportMatrix);
end

%% Set BeliefField At Beginning
total_field = cell(4, 1);
for i = 1:3
    total_field{i, 1} = FillInitialBeliefFieldFromDepth(camera_image{i + 1, 1}, ...
        depth_mats{i, 1}, ...
        depth_mats{i + 1, 1}, ...
        viewportMatrix, ...
        calculation_parameters);
%     total_field{i, 1} = FillInitialBeliefField(camera_image{i+1}, ...
%         pattern, ...
%         depth_mats{i}, ...
%         depth_mats{i+1}, ...
%         lineA, ...
%         lineB, ...
%         lineC, ...
%         viewportMatrix, ...
%         norm_sigma_u, ...
%         voxelSize, ...
%         halfVoxelRange);
end
total_field{4, 1} = FillInitialBeliefField(camera_image{5}, ...
    pattern, ...
    depth_mats{4}, ...
    depth_mats{5}, ...
    lineA, ...
    lineB, ...
    lineC, ...
    viewportMatrix, ...
    calculation_parameters);
save(['total_field', '0', '.mat'], 'total_field');
depthMaps = debugGetDepthFromBeliefField(total_field, ...
    depth_mats, ...
    viewportMatrix, ...
    calculation_parameters);
writepointcloud(depthMaps, ...
    camMat, ...
    'point_cloud/', ...
    ['iter', '0'], ...
    '.txt', ...
    viewportMatrix);

%% Iteration for frame 2-5
for i_idx = 1:10
    total_field = BeliefFieldIterationFast(total_field, ...
        camera_image{2}, ...
        pattern, ...
        depth_mats, ...
        lineA, ...
        lineB, ...
        lineC, ...
        viewportMatrix, ...
        calculation_parameters);
    save(['total_field', num2str(i_idx), '.mat'], 'total_field');
    depthMaps = debugGetDepthFromBeliefField(total_field, ...
        depth_mats, ...
        viewportMatrix, ...
        calculation_parameters);
    writepointcloud(depthMaps, ...
        camMat, ...
        'point_cloud/', ...
        ['iter', num2str(i_idx)], ...
        '.txt', ...
        viewportMatrix);
    fprintf(' %d: iteration.\n', i_idx);
end
