%医学成像实验二
%生成shep-Logan头模型
P=phantom(256);  
imshow(P)
%获得扇形束和头模型的数据
D=200;
F=fanbeam(P,D,'FanRotationIncrement',0.25,'FanSensorSpacing',0.25);
theta=0:1:179;[R4,xp]=radon(P,theta);%平行束投影数据采集显示投影数据：
figure,imshow(F,[]);
title('扇形束投影数据')
figure,imagesc(theta,xp,R4);xlabel('\theta');ylabel('x\prime');
title('平行束180个角度投影数据');
%用MATLAB中的ifanbeam函数实现图像重建；
I=ifanbeam(F,D,'FanSensorSpacing',0.25,'FanRotationIncrement',0.25);
I4=iradon(R4,1);%平行束投影数据重建，显示重建图像
figure,
imshow(I);title('扇形束投影数据重建')
figure,
imshow(I4)
