function fig = omn_constr_final()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.

load omn_constr_final

h0 = figure('Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[232 258 560 420], ...
	'ResizeFcn','doresize(gcbf)', ...
	'ToolBar','figure', ...
	'DefaultaxesCreateFcn','plotedit(gcbf,''promoteoverlay''); ');
h1 = uimenu('Parent',h0, ...
	'HandleVisibility','off', ...
	'Tag','ScribeHGBinObject', ...
	'Visible','off');
h1 = uimenu('Parent',h0, ...
	'HandleVisibility','off', ...
	'Tag','ScribeFigObjStorage', ...
	'Visible','off');
h1 = uimenu('Parent',h0, ...
	'HandleVisibility','off', ...
	'Tag','ScribeHGBinObject', ...
	'Visible','off');
h1 = uimenu('Parent',h0, ...
	'HandleVisibility','off', ...
	'Tag','ScribeHGBinObject', ...
	'Visible','off');
h1 = uimenu('Parent',h0, ...
	'HandleVisibility','off', ...
	'Tag','ScribeHGBinObject', ...
	'Visible','off');
h1 = uimenu('Parent',h0, ...
	'HandleVisibility','off', ...
	'Tag','ScribeFigObjStorage', ...
	'Visible','off');
h1 = uimenu('Parent',h0, ...
	'HandleVisibility','off', ...
	'Tag','ScribeHGBinObject', ...
	'Visible','off');
h1 = uimenu('Parent',h0, ...
	'HandleVisibility','off', ...
	'Tag','ScribeHGBinObject', ...
	'Visible','off');
h1 = uimenu('Parent',h0, ...
	'HandleVisibility','off', ...
	'Tag','ScribeHGBinObject', ...
	'Visible','off');
h1 = uimenu('Parent',h0, ...
	'HandleVisibility','off', ...
	'Tag','ScribeFigObjStorage', ...
	'Visible','off');
h1 = uicontextmenu('Parent',h0, ...
	'Callback','domymenu update', ...
	'HandleVisibility','off', ...
	'Tag','ScribeAxisObjContextMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu cut', ...
	'HandleVisibility','off', ...
	'Label','Cu&t', ...
	'Tag','ScribeAxisObjCutMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu copy', ...
	'HandleVisibility','off', ...
	'Label','&Copy', ...
	'Tag','ScribeAxisObjCopyMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu paste', ...
	'HandleVisibility','off', ...
	'Label','&Paste', ...
	'Tag','ScribeAxisObjPasteMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu clear', ...
	'HandleVisibility','off', ...
	'Label','Clea&r', ...
	'Tag','ScribeAxisObjClearMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu showlegend', ...
	'HandleVisibility','off', ...
	'Label','Show Legend', ...
	'Separator','on', ...
	'Tag','ScribeAxisObjShowLegendMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu moveresize', ...
	'HandleVisibility','off', ...
	'Label','Lock Position', ...
	'Separator','on', ...
	'Tag','ScribeAxisObjMoveResizeMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu more', ...
	'HandleVisibility','off', ...
	'Label','Properties...', ...
	'Separator','on', ...
	'Tag','ScribeAxischildObjMoreMenu');
h1 = uicontextmenu('Parent',h0, ...
	'Callback','domymenu update', ...
	'HandleVisibility','off', ...
	'Tag','ScribeAxistextObjContextMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu cut', ...
	'HandleVisibility','off', ...
	'Label','Cu&t', ...
	'Tag','ScribeAxistextObjCutMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu copy', ...
	'HandleVisibility','off', ...
	'Label','&Copy', ...
	'Tag','ScribeAxistextObjCopyMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu paste', ...
	'Enable','off', ...
	'HandleVisibility','off', ...
	'Label','&Paste', ...
	'Tag','ScribeAxistextObjPasteMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu clear', ...
	'HandleVisibility','off', ...
	'Label','Clea&r', ...
	'Tag','ScribeAxistextObjClearMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu string', ...
	'HandleVisibility','off', ...
	'Label','&String...', ...
	'Separator','on', ...
	'Tag','ScribeAxistextObjStringMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu size', ...
	'HandleVisibility','off', ...
	'Label','&Font Size', ...
	'Tag','ScribeAxistextObjSizeMenu');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 4', ...
	'HandleVisibility','off', ...
	'Label','4', ...
	'Tag','ScribeEditlineObjSizeMenu4');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 6', ...
	'HandleVisibility','off', ...
	'Label','6', ...
	'Tag','ScribeEditlineObjSizeMenu6');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 8', ...
	'HandleVisibility','off', ...
	'Label','8', ...
	'Tag','ScribeEditlineObjSizeMenu8');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 9', ...
	'HandleVisibility','off', ...
	'Label','9', ...
	'Tag','ScribeEditlineObjSizeMenu9');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 10', ...
	'HandleVisibility','off', ...
	'Label','10', ...
	'Tag','ScribeEditlineObjSizeMenu10');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 11', ...
	'HandleVisibility','off', ...
	'Label','11', ...
	'Tag','ScribeEditlineObjSizeMenu11');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 12', ...
	'HandleVisibility','off', ...
	'Label','12', ...
	'Tag','ScribeEditlineObjSizeMenu12');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 14', ...
	'Checked','on', ...
	'HandleVisibility','off', ...
	'Label','14', ...
	'Tag','ScribeEditlineObjSizeMenu14');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 18', ...
	'HandleVisibility','off', ...
	'Label','18', ...
	'Tag','ScribeEditlineObjSizeMenu18');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 24', ...
	'HandleVisibility','off', ...
	'Label','24', ...
	'Tag','ScribeEditlineObjSizeMenu24');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 32', ...
	'HandleVisibility','off', ...
	'Label','32', ...
	'Tag','ScribeEditlineObjSizeMenu32');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu font', ...
	'HandleVisibility','off', ...
	'Label','more...', ...
	'Tag','ScribeEditlineObjSizeMenuMore');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu style', ...
	'HandleVisibility','off', ...
	'Label','Font St&yle', ...
	'Tag','ScribeAxistextObjStyleMenu');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu style normal', ...
	'Checked','on', ...
	'HandleVisibility','off', ...
	'Label','&Normal', ...
	'Tag','ScribeAxistextObjStyleMenuNormal');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu style italic', ...
	'HandleVisibility','off', ...
	'Label','&Italic', ...
	'Tag','ScribeAxistextdObjStyleMenuItalic');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu style bold', ...
	'HandleVisibility','off', ...
	'Label','&Bold', ...
	'Tag','ScribeAxistextObjStyleMenuBold');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu color', ...
	'HandleVisibility','off', ...
	'Label','Co&lor...', ...
	'Tag','ScribeAxistextObjColorMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu font', ...
	'HandleVisibility','off', ...
	'Label','&Properties...', ...
	'Separator','on', ...
	'Tag','ScribeAxistextObjMoreMenu');
h1 = uicontextmenu('Parent',h0, ...
	'Callback','domymenu update', ...
	'HandleVisibility','off', ...
	'Tag','ScribeEditlineObjContextMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu cut', ...
	'HandleVisibility','off', ...
	'Label','Cu&t', ...
	'Tag','ScribeEditlineObjCutMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu copy', ...
	'HandleVisibility','off', ...
	'Label','&Copy', ...
	'Tag','ScribeEditlineObjCopyMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu paste', ...
	'Enable','off', ...
	'HandleVisibility','off', ...
	'Label','&Paste', ...
	'Tag','ScribeEditlineObjPasteMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu clear', ...
	'HandleVisibility','off', ...
	'Label','Clea&r', ...
	'Tag','ScribeEditlineObjClearMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu size', ...
	'HandleVisibility','off', ...
	'Label','Line &Width', ...
	'Separator','on', ...
	'Tag','ScribeEditlineObjSizeMenu');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 0.5', ...
	'Checked','on', ...
	'HandleVisibility','off', ...
	'Label','0.5', ...
	'Tag','ScribeEditlineObjSizeMenu0.5');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 1', ...
	'HandleVisibility','off', ...
	'Label','1', ...
	'Tag','ScribeEditlineObjSizeMenu1');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 2', ...
	'HandleVisibility','off', ...
	'Label','2', ...
	'Tag','ScribeEditlineObjSizeMenu2');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 3', ...
	'HandleVisibility','off', ...
	'Label','3', ...
	'Tag','ScribeEditlineObjSizeMenu3');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 4', ...
	'HandleVisibility','off', ...
	'Label','4', ...
	'Tag','ScribeEditlineObjSizeMenu4');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 5', ...
	'HandleVisibility','off', ...
	'Label','5', ...
	'Tag','ScribeEditlineObjSizeMenu5');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 6', ...
	'HandleVisibility','off', ...
	'Label','6', ...
	'Tag','ScribeEditlineObjSizeMenu6');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 7', ...
	'HandleVisibility','off', ...
	'Label','7', ...
	'Tag','ScribeEditlineObjSizeMenu7');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 8', ...
	'HandleVisibility','off', ...
	'Label','8', ...
	'Tag','ScribeEditlineObjSizeMenu8');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 9', ...
	'HandleVisibility','off', ...
	'Label','9', ...
	'Tag','ScribeEditlineObjSizeMenu9');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 10', ...
	'HandleVisibility','off', ...
	'Label','10', ...
	'Tag','ScribeEditlineObjSizeMenu10');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu more', ...
	'HandleVisibility','off', ...
	'Label','more...', ...
	'Tag','ScribeEditlineObjSizeMenuMore');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu style', ...
	'HandleVisibility','off', ...
	'Label','Line &Style', ...
	'Tag','ScribeEditlineObjStyleMenu');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu style solid', ...
	'Checked','on', ...
	'HandleVisibility','off', ...
	'Label','solid', ...
	'Tag','ScribeEditlineObjStyleMenuSolid');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu style dash', ...
	'HandleVisibility','off', ...
	'Label','dash', ...
	'Tag','ScribeEditlineObjStyleMenuDash');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu style dot', ...
	'HandleVisibility','off', ...
	'Label','dot', ...
	'Tag','ScribeEditlineObjStyleMenuDot');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu style dashdot', ...
	'HandleVisibility','off', ...
	'Label','dash-dot', ...
	'Tag','ScribeEditlineObjStyleMenuDashDot');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu color', ...
	'HandleVisibility','off', ...
	'Label','Color...', ...
	'Tag','ScribeEditlineObjColorMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu more', ...
	'HandleVisibility','off', ...
	'Label','Properties...', ...
	'Separator','on', ...
	'Tag','ScribeEditlineObjMoreMenu');
h1 = axes('Parent',h0, ...
	'Box','on', ...
	'CameraUpVector',[0 1 0], ...
	'CameraUpVectorMode','manual', ...
	'Color',[1 1 1], ...
	'ColorOrder',mat1, ...
	'CreateFcn','', ...
	'Position',[0.13 0.11 0.7749999999999998 0.3439017341040462], ...
	'XColor',[0 0 0], ...
	'YColor',[0 0 0], ...
	'ZColor',[0 0 0]);
h2 = line('Parent',h1, ...
	'Color',[0 0 1], ...
	'LineWidth',2, ...
	'XData',mat2, ...
	'YData',mat3);
h2 = line('Parent',h1, ...
	'Color',[1 0 0], ...
	'LineStyle','none', ...
	'LineWidth',1, ...
	'Marker','.', ...
	'MarkerSize',16, ...
	'XData',mat4, ...
	'YData',mat5);
h2 = line('Parent',h1, ...
	'Color',[0 0 0], ...
	'XData',mat6, ...
	'YData',mat7);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'FontSize',14, ...
	'FontWeight','bold', ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[-0.006928406466511827 -0.1597222222222219 17.32050807568877], ...
	'String',mat8, ...
	'VerticalAlignment','cap');
set(get(h2,'Parent'),'XLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[-3.401847575057737 0.4930555555555558 17.32050807568877], ...
	'Rotation',90, ...
	'VerticalAlignment','baseline');
set(get(h2,'Parent'),'YLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','right', ...
	'Position',[-4.02540415704388 2.583333333333334 17.32050807568877], ...
	'Visible','off');
set(get(h2,'Parent'),'ZLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'DeleteFcn','eval(''delete(get(gcbo,''''userdata''''))'','''')', ...
	'HandleVisibility','off', ...
	'Tag','LegendDeleteProxy', ...
	'UserData',265.0010986328125, ...
	'Visible','off');
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[-0.006928406466511827 1.041666666666667 17.32050807568877], ...
	'VerticalAlignment','bottom');
set(get(h2,'Parent'),'Title',h2);
h1 = axes('Parent',h0, ...
	'Box','on', ...
	'CameraUpVector',[0 1 0], ...
	'CameraUpVectorMode','manual', ...
	'CLimMode','manual', ...
	'Color',[1 1 1], ...
	'ColorOrder',mat9, ...
	'CreateFcn','plotedit(gcbf,''promoteoverlay''); ', ...
	'DeleteFcn','legend(''DeleteLegend'')', ...
	'DrawMode','fast', ...
	'NextPlot','add', ...
	'Position',[0.7573809523809523 0.3105287182310303 0.1357142857142857 0.1275], ...
	'Tag','legend', ...
	'UserData',mat10, ...
	'Visible','off', ...
	'XColor',[0 0 0], ...
	'XLimMode','manual', ...
	'XTick',-1, ...
	'XTickLabelMode','manual', ...
	'XTickMode','manual', ...
	'YColor',[0 0 0], ...
	'YLimMode','manual', ...
	'YTick',-1, ...
	'YTickLabelMode','manual', ...
	'YTickMode','manual', ...
	'ZColor',[0 0 0]);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'Position',[0.5043859649122807 0.5 0], ...
	'String',['z(x)         ';'z_{\delta}(x)';'H=-2         '], ...
	'Visible','off');
h2 = line('Parent',h1, ...
	'Color',[0 0 1], ...
	'LineWidth',2, ...
	'Visible','off', ...
	'XData',mat11, ...
	'YData',[0.8092592592592592 0.8092592592592592]);
h2 = line('Parent',h1, ...
	'Color',[1 0 0], ...
	'LineWidth',1, ...
	'Visible','off', ...
	'XData',mat12, ...
	'YData',[0.4944444444444445 0.4944444444444445]);
h2 = line('Parent',h1, ...
	'Color',[1 0 0], ...
	'LineStyle','none', ...
	'LineWidth',1, ...
	'Marker','.', ...
	'MarkerSize',10, ...
	'Visible','off', ...
	'XData',0.2521929824561404, ...
	'YData',0.4944444444444445);
h2 = line('Parent',h1, ...
	'Color',[0 0 0], ...
	'Visible','off', ...
	'XData',mat13, ...
	'YData',[0.1796296296296296 0.1796296296296296]);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[0.4933333333333332 -0.1509433962264151 9.160254037844386], ...
	'VerticalAlignment','cap', ...
	'Visible','off');
set(get(h2,'Parent'),'XLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[-0.09333333333333282 0.4716981132075473 9.160254037844386], ...
	'Rotation',90, ...
	'VerticalAlignment','baseline', ...
	'Visible','off');
set(get(h2,'Parent'),'YLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','right', ...
	'Position',[-5.666666666666667 5.433962264150943 9.160254037844386], ...
	'Visible','off');
set(get(h2,'Parent'),'ZLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[0.4933333333333332 1.113207547169811 9.160254037844386], ...
	'VerticalAlignment','bottom', ...
	'Visible','off');
set(get(h2,'Parent'),'Title',h2);
h1 = axes('Parent',h0, ...
	'Box','on', ...
	'CameraUpVector',[0 1 0], ...
	'CameraUpVectorMode','manual', ...
	'Color',[1 1 1], ...
	'ColorOrder',mat14, ...
	'CreateFcn','plotedit(gcbf,''promoteoverlay''); ', ...
	'Position',[0.13 0.5810982658959537 0.7749999999999999 0.3439017341040462], ...
	'XColor',[0 0 0], ...
	'XLim',[0.3 10], ...
	'XLimMode','manual', ...
	'XScale','log', ...
	'YColor',[0 0 0], ...
	'ZColor',[0 0 0]);
h2 = line('Parent',h1, ...
	'Color',[0 0 1], ...
	'LineWidth',1, ...
	'Marker','.', ...
	'XData',[0.5555555555555556 1 1.8 3.24 5.832000000000001], ...
	'YData',[0.07251651790293669 0.03744704643951111 0.01030365240083301 0.009764993338066847 0.009764993338066847]);
h2 = line('Parent',h1, ...
	'Color',[1 0 0], ...
	'Marker','.', ...
	'XData',[0.5555555555555556 1 1.8 3.24 5.832000000000001], ...
	'YData',mat15);
h2 = line('Parent',h1, ...
	'Color',[0 0 0], ...
	'XData',[1.8 1.8], ...
	'YData',[0 0.08]);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',mat16, ...
	'VerticalAlignment','bottom');
set(get(h2,'Parent'),'Title',h2);
h2 = text('Parent',h1, ...
	'Units','normalized', ...
	'Color',[0 0 0], ...
	'FontSize',14, ...
	'FontWeight','bold', ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[0.6912442396313364 -0.0625 0], ...
	'String',mat17, ...
	'VerticalAlignment','cap');
set(get(h2,'Parent'),'XLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[0.2241340193746751 0.03916083916083916 17.32050807568877], ...
	'Rotation',90, ...
	'VerticalAlignment','baseline');
set(get(h2,'Parent'),'YLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','right', ...
	'Position',mat18, ...
	'Visible','off');
set(get(h2,'Parent'),'ZLabel',h2);
h1 = axes('Parent',h0, ...
	'CameraUpVector',[0 1 0], ...
	'CameraUpVectorMode','manual', ...
	'Color','none', ...
	'ColorOrder',mat19, ...
	'CreateFcn','', ...
	'HandleVisibility','off', ...
	'HitTest','off', ...
	'Position',[0 0 1 1], ...
	'Tag','ScribeOverlayAxesActive', ...
	'Visible','off', ...
	'XColor',[0.8 0.8 0.8], ...
	'XLimMode','manual', ...
	'XTickMode','manual', ...
	'YColor',[0.8 0.8 0.8], ...
	'YLimMode','manual', ...
	'YTickMode','manual', ...
	'ZColor',[0 0 0]);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'FontSize',14, ...
	'FontWeight','bold', ...
	'Position',[0.5410714285714287 0.680952380952381 0], ...
	'String','C_{\eta}  ');
h2 = text('Parent',h1, ...
	'ButtonDownFcn','scriberestoresavefcns', ...
	'Color',[0 0 0], ...
	'FontSize',14, ...
	'FontWeight','bold', ...
	'Position',[0.3642857142857143 0.8404761904761905 0], ...
	'String','\beta_{\eta}(C) ');
h2 = text('Parent',h1, ...
	'ButtonDownFcn','scriberestoresavefcns', ...
	'Color',[0 0 0], ...
	'FontSize',14, ...
	'FontWeight','bold', ...
	'Position',[0.2767857142857143 0.6714285714285715 0], ...
	'String','\Pi_{\eta}(C)  ');
h2 = text('Parent',h1, ...
	'Color',[0.8 0.8 0.8], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[0.4991055456171735 -0.01909307875895006 9.160254037844386], ...
	'VerticalAlignment','cap', ...
	'Visible','off');
set(get(h2,'Parent'),'XLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0.8 0.8 0.8], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[-0.01252236135957066 0.4964200477326969 9.160254037844386], ...
	'Rotation',90, ...
	'VerticalAlignment','baseline', ...
	'Visible','off');
set(get(h2,'Parent'),'YLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','right', ...
	'Position',[-0.001788908765652952 0.9976133651551312 9.160254037844386], ...
	'Visible','off');
set(get(h2,'Parent'),'ZLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',mat20, ...
	'VerticalAlignment','bottom', ...
	'Visible','off');
set(get(h2,'Parent'),'Title',h2);
if nargout > 0, fig = h0; end
