function Hd = LP_P90_S100_N101
%LP_P90_S100_N101 返回离散时间滤波器对象。

% MATLAB Code
% Generated by MATLAB(R) 9.8 and DSP System Toolbox 9.10.
% Generated on: 31-May-2021 10:40:27

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in MHz.
Fs = 400;  % Sampling Frequency

N     = 100;  % Order
Fpass = 90;   % Passband Frequency
Fstop = 100;  % Stopband Frequency
Wpass = 1;    % Passband Weight
Wstop = 1;    % Stopband Weight
dens  = 20;   % Density Factor

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, [0 Fpass Fstop Fs/2]/(Fs/2), [1 1 0 0], [Wpass Wstop], ...
           {dens});
Hd = dfilt.dffir(b);

% [EOF]
