function C = helpmaintxt
% filename: helpmaintxt.m
% Project: Array2d
% Description:  This program contains the text displayed in the Array2d 
%			Main Help GUI.
% Author:  Prof. David C. Jenn 
% Date: 23 July 2002
% Place: NPS
%
 C   =  {'ARRAY2D: Two dimensional planar array pattern calculation';...
			' ';...
			'Brief description of the simulation and quantities:';...
			' ';...
			'This program computes the array factor for a two dimensional';...
			'planar array with rectangular element spacing.  The array';...
			'lies in the x-y plane.  Amplitude distributions can be sel-';...
			'ected independently for the x and y dimensions (i.e., the';...
			'amplitude distribution is separable). The beam can be scanned';...
			'relative to the positive z axis.  Standard spherical angles';...
			'theta and phi are used throughout. If either theta or phi is';...
			'constant (i.e., start and stop values the same) a pattern cut';...
			'is plotted. If both theta and phi vary then a two dimensional';...
			'pattern is plotted in direction cosine space:';...
			'        U = sin(theta)*cos(phi)';...
			'        V = sin(theta)*sin(phi)';... 
			' ';...
			'Quantities:';...
			'Nx, Ny = number of elements in the x and y directions';...
			'    (if one of them =1 then a linear array results)';...
			'dx, dy = spacings in the x and y directions in wavelengths';...
			'    (for a linear array the unused spacing should be 0)';...
			'thetas, phis = scan angle from the z axis in degrees';...
			' ';...
			'Amplitude distributions:';...
			'Uniform - sidelobe level approximately -13 dB';...
			'Taylor - parameters SLL (sidelobe level, denoted by peddb)';...
			'       and nbar which controls the rate of fall off of the';...
			'       sidelobes, N > nbar > 5)';...
			'Cosine-on-a-pedestal -  the pedestal height and cosine exp-';...
			'       onent control the sidelobe level and rate of falloff.';...
			'       An exp = 2 and 10 dB pedestal gives about -32 dB SLL.';...
			'Triangular - linear amplitude taper from 1 at the center to';...
			'       0 at the edges';...
            'Bayliss - for monopulse difference beams with parameters the';...
            '       same as those for the Taylor distribution';...
			' ';...
            'Phase shifter roundoff:';...
			'Digital phase shifter roundoff can be simulated. The number';...
			'of bits can be selected from the pulldown menu.  The phase';...
			'step is determined from the bit size:';...
			'              phase step = 360/(2^bits)';...
			'Round off methods can be selected:';...
			'Exact phase - no roundoff (the number of bits is ignored)';...
			'Truncation - the phase is truncated to the closet lowest';...
			'      phase state (modulo phase step)';...
			'Random roundoff - the phase setting is chosen randomly between';...
			'      the closest upper and lower phase steps';...
			'Weighted random roundoff - the phase setting is chosen randomly';...
			'      between the closest upper and lower steps, but with higher';...
			'      probability for the closest of the two based on a uniform';...
			'      probability density function.';...
            ' ';...
			'DISCLAIMER: This code was created for instructional purposes.';...
			'Basic test geometries have been validated, however, there is';...
			'no guarantee of accuracy in all cases.';
         ' ';};