function fig = vessel_pic1()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.

load vessel_pic1

h0 = figure('Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[232 258 560 420], ...
	'ResizeFcn','doresize(gcbf)', ...
	'ToolBar','figure', ...
	'DefaultaxesCreateFcn','plotedit(gcbf,''promoteoverlay''); ');
h1 = uimenu('Parent',h0, ...
	'HandleVisibility','off', ...
	'Tag','ScribeHGBinObject', ...
	'Visible','off');
h1 = uimenu('Parent',h0, ...
	'HandleVisibility','off', ...
	'Tag','ScribeFigObjStorage', ...
	'Visible','off');
h1 = uimenu('Parent',h0, ...
	'HandleVisibility','off', ...
	'Tag','ScribeHGBinObject', ...
	'Visible','off');
h1 = uimenu('Parent',h0, ...
	'HandleVisibility','off', ...
	'Tag','ScribeHGBinObject', ...
	'Visible','off');
h1 = uimenu('Parent',h0, ...
	'HandleVisibility','off', ...
	'Tag','ScribeHGBinObject', ...
	'Visible','off');
h1 = uimenu('Parent',h0, ...
	'HandleVisibility','off', ...
	'Tag','ScribeFigObjStorage', ...
	'Visible','off');
h1 = axes('Parent',h0, ...
	'Box','on', ...
	'CameraUpVector',[0 1 0], ...
	'CameraUpVectorMode','manual', ...
	'Color',[1 1 1], ...
	'ColorOrder',mat1, ...
	'CreateFcn','plotedit(gcbf,''promoteoverlay''); ', ...
	'DataAspectRatioMode','manual', ...
	'PlotBoxAspectRatio',[183.1329479768785 342.3 366.2658959537571], ...
	'PlotBoxAspectRatioMode','manual', ...
	'Position',[0.208 0.11 0.327023 0.815], ...
	'WarpToFill','off', ...
	'WarpToFillMode','manual', ...
	'XColor',[0 0 0], ...
	'XDir','reverse', ...
	'YColor',[0 0 0], ...
	'ZColor',[0 0 0]);
h2 = line('Parent',h1, ...
	'Color',[0 0 1], ...
	'XData',mat2, ...
	'YData',mat3);
h2 = line('Parent',h1, ...
	'Color',[1 0 0], ...
	'XData',mat4, ...
	'YData',mat5);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',mat6, ...
	'VerticalAlignment','bottom');
set(get(h2,'Parent'),'Title',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',mat7, ...
	'VerticalAlignment','cap');
set(get(h2,'Parent'),'XLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',mat8, ...
	'Rotation',90, ...
	'VerticalAlignment','baseline');
set(get(h2,'Parent'),'YLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','right', ...
	'Position',mat9, ...
	'Visible','off');
set(get(h2,'Parent'),'ZLabel',h2);
h1 = axes('Parent',h0, ...
	'Box','on', ...
	'CameraUpVector',[0 1 0], ...
	'CameraUpVectorMode','manual', ...
	'Color',[1 1 1], ...
	'ColorOrder',mat10, ...
	'CreateFcn','plotedit(gcbf,''promoteoverlay''); ', ...
	'DataAspectRatioMode','manual', ...
	'FontName','Arial Cyr', ...
	'PlotBoxAspectRatio',[183.1329479768785 342.3 366.2658959537571], ...
	'PlotBoxAspectRatioMode','manual', ...
	'Position',[0.5 0.11 0.327023 0.815], ...
	'WarpToFill','off', ...
	'WarpToFillMode','manual', ...
	'XColor',[0 0 0], ...
	'XTickLabelMode','manual', ...
	'YColor',[0 0 0], ...
	'YTick',[-1 1], ...
	'YTickLabelMode','manual', ...
	'YTickMode','manual', ...
	'ZColor',[0 0 0]);
h2 = line('Parent',h1, ...
	'Color',[0 0 1], ...
	'XData',mat11, ...
	'YData',mat12);
h2 = line('Parent',h1, ...
	'Color',[0 0 0], ...
	'LineStyle','none', ...
	'Marker','.', ...
	'XData',mat13, ...
	'YData',mat14);
h2 = line('Parent',h1, ...
	'Color',[0 0 0], ...
	'XData',[0 0], ...
	'YData',[-1 1]);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'FontName','Arial Cyr', ...
	'Position',[0.8454229468277468 0.4326179029150296 0], ...
	'String',' 2');
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'FontName','Arial Cyr', ...
	'Position',[0.8509295088620422 0.8770659382186555 0], ...
	'String',' 6');
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'FontName','Arial Cyr', ...
	'Position',[0.6112 0.7895 0], ...
	'String',' 3');
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'FontName','Arial Cyr', ...
	'Position',[0.6228941453891549 0.3040620088259065 0], ...
	'String','4');
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'FontName','Arial Cyr', ...
	'Position',[0.4122763457488028 -0.4560899558704679 0], ...
	'String','5');
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'FontName','Arial Cyr', ...
	'Position',[0.09727119856140817 -0.8889 0], ...
	'String',' 7');
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'FontName','Arial Cyr', ...
	'Position',[0.8043234184433802 -0.7720580794331574 0], ...
	'String',' 1');
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',mat15, ...
	'VerticalAlignment','cap');
set(get(h2,'Parent'),'XLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',mat16, ...
	'Rotation',90, ...
	'VerticalAlignment','baseline');
set(get(h2,'Parent'),'YLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','right', ...
	'Position',mat17, ...
	'Visible','off');
set(get(h2,'Parent'),'ZLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',mat18, ...
	'VerticalAlignment','bottom');
set(get(h2,'Parent'),'Title',h2);
h1 = uicontextmenu('Parent',h0, ...
	'Callback','domymenu update', ...
	'HandleVisibility','off', ...
	'Tag','ScribeAxisObjContextMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu cut', ...
	'HandleVisibility','off', ...
	'Label','Cu&t', ...
	'Tag','ScribeAxisObjCutMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu copy', ...
	'HandleVisibility','off', ...
	'Label','&Copy', ...
	'Tag','ScribeAxisObjCopyMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu paste', ...
	'HandleVisibility','off', ...
	'Label','&Paste', ...
	'Tag','ScribeAxisObjPasteMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu clear', ...
	'HandleVisibility','off', ...
	'Label','Clea&r', ...
	'Tag','ScribeAxisObjClearMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu showlegend', ...
	'HandleVisibility','off', ...
	'Label','Show Legend', ...
	'Separator','on', ...
	'Tag','ScribeAxisObjShowLegendMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu moveresize', ...
	'HandleVisibility','off', ...
	'Label','Lock Position', ...
	'Separator','on', ...
	'Tag','ScribeAxisObjMoveResizeMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu more', ...
	'HandleVisibility','off', ...
	'Label','Properties...', ...
	'Separator','on', ...
	'Tag','ScribeAxischildObjMoreMenu');
h1 = uicontextmenu('Parent',h0, ...
	'Callback','domymenu update', ...
	'HandleVisibility','off', ...
	'Tag','ScribeAxistextObjContextMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu cut', ...
	'HandleVisibility','off', ...
	'Label','Cu&t', ...
	'Tag','ScribeAxistextObjCutMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu copy', ...
	'HandleVisibility','off', ...
	'Label','&Copy', ...
	'Tag','ScribeAxistextObjCopyMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu paste', ...
	'Enable','off', ...
	'HandleVisibility','off', ...
	'Label','&Paste', ...
	'Tag','ScribeAxistextObjPasteMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu clear', ...
	'HandleVisibility','off', ...
	'Label','Clea&r', ...
	'Tag','ScribeAxistextObjClearMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu string', ...
	'HandleVisibility','off', ...
	'Label','&String...', ...
	'Separator','on', ...
	'Tag','ScribeAxistextObjStringMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu size', ...
	'HandleVisibility','off', ...
	'Label','&Font Size', ...
	'Tag','ScribeAxistextObjSizeMenu');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 4', ...
	'HandleVisibility','off', ...
	'Label','4', ...
	'Tag','ScribeEditlineObjSizeMenu4');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 6', ...
	'HandleVisibility','off', ...
	'Label','6', ...
	'Tag','ScribeEditlineObjSizeMenu6');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 8', ...
	'HandleVisibility','off', ...
	'Label','8', ...
	'Tag','ScribeEditlineObjSizeMenu8');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 9', ...
	'HandleVisibility','off', ...
	'Label','9', ...
	'Tag','ScribeEditlineObjSizeMenu9');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 10', ...
	'Checked','on', ...
	'HandleVisibility','off', ...
	'Label','10', ...
	'Tag','ScribeEditlineObjSizeMenu10');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 11', ...
	'HandleVisibility','off', ...
	'Label','11', ...
	'Tag','ScribeEditlineObjSizeMenu11');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 12', ...
	'HandleVisibility','off', ...
	'Label','12', ...
	'Tag','ScribeEditlineObjSizeMenu12');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 14', ...
	'HandleVisibility','off', ...
	'Label','14', ...
	'Tag','ScribeEditlineObjSizeMenu14');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 18', ...
	'HandleVisibility','off', ...
	'Label','18', ...
	'Tag','ScribeEditlineObjSizeMenu18');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 24', ...
	'HandleVisibility','off', ...
	'Label','24', ...
	'Tag','ScribeEditlineObjSizeMenu24');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 32', ...
	'HandleVisibility','off', ...
	'Label','32', ...
	'Tag','ScribeEditlineObjSizeMenu32');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu font', ...
	'HandleVisibility','off', ...
	'Label','more...', ...
	'Tag','ScribeEditlineObjSizeMenuMore');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu style', ...
	'HandleVisibility','off', ...
	'Label','Font St&yle', ...
	'Tag','ScribeAxistextObjStyleMenu');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu style normal', ...
	'Checked','on', ...
	'HandleVisibility','off', ...
	'Label','&Normal', ...
	'Tag','ScribeAxistextObjStyleMenuNormal');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu style italic', ...
	'HandleVisibility','off', ...
	'Label','&Italic', ...
	'Tag','ScribeAxistextdObjStyleMenuItalic');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu style bold', ...
	'HandleVisibility','off', ...
	'Label','&Bold', ...
	'Tag','ScribeAxistextObjStyleMenuBold');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu color', ...
	'HandleVisibility','off', ...
	'Label','Co&lor...', ...
	'Tag','ScribeAxistextObjColorMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu font', ...
	'HandleVisibility','off', ...
	'Label','&Properties...', ...
	'Separator','on', ...
	'Tag','ScribeAxistextObjMoreMenu');
h1 = uicontextmenu('Parent',h0, ...
	'Callback','domymenu update', ...
	'HandleVisibility','off', ...
	'Tag','ScribeEditlineObjContextMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu cut', ...
	'HandleVisibility','off', ...
	'Label','Cu&t', ...
	'Tag','ScribeEditlineObjCutMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu copy', ...
	'HandleVisibility','off', ...
	'Label','&Copy', ...
	'Tag','ScribeEditlineObjCopyMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu paste', ...
	'HandleVisibility','off', ...
	'Label','&Paste', ...
	'Tag','ScribeEditlineObjPasteMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu clear', ...
	'HandleVisibility','off', ...
	'Label','Clea&r', ...
	'Tag','ScribeEditlineObjClearMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu size', ...
	'HandleVisibility','off', ...
	'Label','Line &Width', ...
	'Separator','on', ...
	'Tag','ScribeEditlineObjSizeMenu');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 0.5', ...
	'HandleVisibility','off', ...
	'Label','0.5', ...
	'Tag','ScribeEditlineObjSizeMenu0.5');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 1', ...
	'HandleVisibility','off', ...
	'Label','1', ...
	'Tag','ScribeEditlineObjSizeMenu1');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 2', ...
	'HandleVisibility','off', ...
	'Label','2', ...
	'Tag','ScribeEditlineObjSizeMenu2');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 3', ...
	'HandleVisibility','off', ...
	'Label','3', ...
	'Tag','ScribeEditlineObjSizeMenu3');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 4', ...
	'HandleVisibility','off', ...
	'Label','4', ...
	'Tag','ScribeEditlineObjSizeMenu4');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 5', ...
	'HandleVisibility','off', ...
	'Label','5', ...
	'Tag','ScribeEditlineObjSizeMenu5');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 6', ...
	'HandleVisibility','off', ...
	'Label','6', ...
	'Tag','ScribeEditlineObjSizeMenu6');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 7', ...
	'HandleVisibility','off', ...
	'Label','7', ...
	'Tag','ScribeEditlineObjSizeMenu7');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 8', ...
	'HandleVisibility','off', ...
	'Label','8', ...
	'Tag','ScribeEditlineObjSizeMenu8');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 9', ...
	'HandleVisibility','off', ...
	'Label','9', ...
	'Tag','ScribeEditlineObjSizeMenu9');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 10', ...
	'HandleVisibility','off', ...
	'Label','10', ...
	'Tag','ScribeEditlineObjSizeMenu10');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu more', ...
	'HandleVisibility','off', ...
	'Label','more...', ...
	'Tag','ScribeEditlineObjSizeMenuMore');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu style', ...
	'HandleVisibility','off', ...
	'Label','Line &Style', ...
	'Tag','ScribeEditlineObjStyleMenu');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu style solid', ...
	'HandleVisibility','off', ...
	'Label','solid', ...
	'Tag','ScribeEditlineObjStyleMenuSolid');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu style dash', ...
	'HandleVisibility','off', ...
	'Label','dash', ...
	'Tag','ScribeEditlineObjStyleMenuDash');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu style dot', ...
	'HandleVisibility','off', ...
	'Label','dot', ...
	'Tag','ScribeEditlineObjStyleMenuDot');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu style dashdot', ...
	'HandleVisibility','off', ...
	'Label','dash-dot', ...
	'Tag','ScribeEditlineObjStyleMenuDashDot');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu color', ...
	'HandleVisibility','off', ...
	'Label','Color...', ...
	'Tag','ScribeEditlineObjColorMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu more', ...
	'HandleVisibility','off', ...
	'Label','Properties...', ...
	'Separator','on', ...
	'Tag','ScribeEditlineObjMoreMenu');
h1 = axes('Parent',h0, ...
	'CameraUpVector',[0 1 0], ...
	'CameraUpVectorMode','manual', ...
	'Color','none', ...
	'ColorOrder',mat19, ...
	'CreateFcn','', ...
	'HandleVisibility','off', ...
	'HitTest','off', ...
	'Position',[0 0 1 1], ...
	'Tag','ScribeOverlayAxesActive', ...
	'Visible','off', ...
	'XColor',[0.8 0.8 0.8], ...
	'XLimMode','manual', ...
	'XTickMode','manual', ...
	'YColor',[0.8 0.8 0.8], ...
	'YLimMode','manual', ...
	'YTickMode','manual', ...
	'ZColor',[0 0 0]);
h2 = text('Parent',h1, ...
	'Color',[0.8 0.8 0.8], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[0.4991055456171735 -0.01909307875895006 17.32050807568877], ...
	'VerticalAlignment','cap', ...
	'Visible','off');
set(get(h2,'Parent'),'XLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0.8 0.8 0.8], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[-0.01252236135957066 0.4964200477326969 17.32050807568877], ...
	'Rotation',90, ...
	'VerticalAlignment','baseline', ...
	'Visible','off');
set(get(h2,'Parent'),'YLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','right', ...
	'Position',[-0.001788908765652952 0.9976133651551312 17.32050807568877], ...
	'Visible','off');
set(get(h2,'Parent'),'ZLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',mat20, ...
	'VerticalAlignment','bottom', ...
	'Visible','off');
set(get(h2,'Parent'),'Title',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'FontWeight','bold', ...
	'Position',[0.525 0.8595238095238096 0], ...
	'String','Z ');
h2 = line('Parent',h1, ...
	'ButtonDownFcn','scriberestoresavefcns', ...
	'Color',[0 0 0], ...
	'LineStyle','none', ...
	'Tag','ScribeArrowlineObject', ...
	'UserData','1.350020e+002', ...
	'XData',[0.5125 0.5125], ...
	'YData',mat21);
h2 = line('Parent',h1, ...
	'Color',[0 0 0], ...
	'Tag','ScribeArrowlineBody', ...
	'UserData','1.350020e+002', ...
	'XData',[0.5125 0.5125], ...
	'YData',mat22);
h2 = patch('Parent',h1, ...
	'FaceColor',[0 0 0], ...
	'Faces',[1 2 3 4 5], ...
	'NormalMode','manual', ...
	'Tag','ScribeArrowlineHead', ...
	'UserData','1.350020e+002', ...
	'VertexNormals',mat23, ...
	'Vertices',mat24);
h2 = line('Parent',h1, ...
	'Color',[0 0 0], ...
	'LineStyle','none', ...
	'Tag','ScribeArrowlineObject', ...
	'UserData','1.680001e+002', ...
	'XData',[0.5125 0.8250000000000001], ...
	'YData',mat25);
h2 = line('Parent',h1, ...
	'Color',[0 0 0], ...
	'Tag','ScribeArrowlineBody', ...
	'UserData','1.680001e+002', ...
	'XData',[0.5125 0.8107142857142858], ...
	'YData',mat26);
h2 = patch('Parent',h1, ...
	'FaceColor',[0 0 0], ...
	'Faces',[1 2 3 4 5], ...
	'Tag','ScribeArrowlineHead', ...
	'UserData','1.680001e+002', ...
	'VertexNormals',mat27, ...
	'Vertices',mat28);
h2 = text('Parent',h1, ...
	'ButtonDownFcn','scriberestoresavefcns', ...
	'Color',[0 0 0], ...
	'FontSize',14, ...
	'Position',[0.8071428571428573 0.07142857142857136 0], ...
	'String','r ');
h2 = line('Parent',h1, ...
	'Color',[0 0 0], ...
	'XData',[0.7839285714285714 0.7839285714285714], ...
	'YData',[0.9214285714285714 0.8976190476190475]);
h2 = line('Parent',h1, ...
	'Color',[0 0 0], ...
	'XData',[0.8142857142857143 0.7964285714285714], ...
	'YData',[0.6928571428571427 0.6928571428571427]);
h2 = line('Parent',h1, ...
	'Color',[0 0 0], ...
	'XData',[0.7535714285714287 0.7303571428571428], ...
	'YData',[0.8357142857142857 0.8357142857142855]);
h2 = line('Parent',h1, ...
	'Color',[0 0 0], ...
	'XData',[0.7535714285714287 0.7232142857142858], ...
	'YData',[0.6404761904761903 0.6404761904761903]);
h2 = line('Parent',h1, ...
	'Color',[0 0 0], ...
	'XData',[0.6821428571428572 0.6571428571428574], ...
	'YData',[0.288095238095238 0.3142857142857143]);
h2 = line('Parent',h1, ...
	'Color',[0 0 0], ...
	'XData',[0.7357142857142858 0.755357142857143], ...
	'YData',[0.2428571428571428 0.2214285714285714]);
h2 = line('Parent',h1, ...
	'Color',[0 0 0], ...
	'XData',[0.5107142857142857 0.5410714285714285], ...
	'YData',[0.1499999999999999 0.1499999999999999]);
if nargout > 0, fig = h0; end
