% Samuel Rivera
%
% customHandPlots

function customFacePlots( faceCoordinates, small )

markSize = 2;
lWidth = 1;

if size(faceCoordinates,1) ~= 2
    faceCoordinates = faceCoordinates';
end

hold on

if size( faceCoordinates,2) == 77

       
   estLeye = faceCoordinates(:,1:9);
   plot( estLeye(1,[2:end, 2]), estLeye(2,[2:end, 2]),...
               '-go','LineWidth',lWidth,...
               'MarkerEdgeColor','k',...
               'MarkerFaceColor','w',...
               'MarkerSize',markSize);

   estReye = faceCoordinates(:,10:18);
   plot( estReye(1,[2:end, 2]), estReye(2,[2:end, 2]),...
               '-go','LineWidth',lWidth,...
               'MarkerEdgeColor','k',...
               'MarkerFaceColor','w',...
               'MarkerSize',markSize);

   estLbrow = faceCoordinates(:,19:26);
   plot( estLbrow(1,[1:end 1]), estLbrow(2,[1:end 1]), ...
               '-go','LineWidth',lWidth,...
               'MarkerEdgeColor','k',...
               'MarkerFaceColor','w',...
               'MarkerSize',markSize);

   estRbrow = faceCoordinates(:,27:34);
   plot( estRbrow(1,[1:end 1]), estRbrow(2,[1:end 1]), ...
               '-go','LineWidth',lWidth,...
               'MarkerEdgeColor','k',...
               'MarkerFaceColor','w',...
               'MarkerSize',markSize);

   estN = faceCoordinates(:,35:49);

   plot( estN(1,1:4), estN(2,1:4), ...
               '-go','LineWidth',lWidth,...
               'MarkerEdgeColor','k',...
               'MarkerFaceColor','w',...
               'MarkerSize',markSize);
   plot( estN(1,5:end), estN(2,5:end), ...
               '-go','LineWidth',lWidth,...
               'MarkerEdgeColor','k',...
               'MarkerFaceColor','w',...
               'MarkerSize',markSize);

   estM = faceCoordinates(:,50:63);
   plot( estM(1,[ 1:end-6 1 ]), estM(2,[1:end-6 1 ] ), ...
               '-go','LineWidth',lWidth,...
               'MarkerEdgeColor','k',...
               'MarkerFaceColor','w',...
               'MarkerSize',markSize);
    plot( estM(1,[1 9:11 5 (end-2):end 1]), estM(2,[1 9:11 5 ...
                            (end-2):end 1 ]), ...
               '-go','LineWidth',lWidth,...
               'MarkerEdgeColor','k',...
               'MarkerFaceColor','w',...
               'MarkerSize',markSize);

   estC = faceCoordinates(:,64:77);
   plot( estC(1,[1:end 1]), estC(2,[1:end 1]), ...
               '-go','LineWidth',lWidth,...
               'MarkerEdgeColor','k',...
               'MarkerFaceColor','w',...
               'MarkerSize',markSize);

   %following code deals with output range.  
    if ~isempty( small )
       minX = min( faceCoordinates(1,:) );
       maxX = max( faceCoordinates(1,:) );
       minY = min( faceCoordinates(2,:) );
       maxY = max( faceCoordinates(2,:) );

        if small == 1
            axis( [ minX-10 maxX+10 minY-17 maxY+10] );
        elseif small == 2
            axis( [ minX-5 maxX+5 minY-8 maxY+5] );
        elseif small ==3
            axis( [ minX-2 maxX+2 minY-4 maxY+2] )
        elseif small == 0
            axis( [ minX-20 maxX+20 minY-35 maxY+20] );
        end

        if small == 1
            rect = [5, 5, 800, 800];
            set(gcf,'Position', rect )
        elseif small == 2
            rect = [5, 5, 1200, 1200];
            set(gcf,'Position', rect ) 
        elseif small == 3
            rect = [5, 5, 2200, 2200];
            set(gcf,'Position', rect ) 
        end
    end
    
elseif size( faceCoordinates,2) == 130

   estLeye = faceCoordinates(:,1:13);
   plot( estLeye(1,[2:end, 2]), estLeye(2,[2:end, 2]),...
               '-go','LineWidth',lWidth,...
               'MarkerEdgeColor','k',...
               'MarkerFaceColor','w',...
               'MarkerSize',markSize);

   estReye = faceCoordinates(:,14:26);
   plot( estReye(1,[2:end, 2]), estReye(2,[2:end, 2]),...
               '-go','LineWidth',lWidth,...
               'MarkerEdgeColor','k',...
               'MarkerFaceColor','w',...
               'MarkerSize',markSize);

   estLbrow = faceCoordinates(:,27:38);
   plot( estLbrow(1,[1:end 1]), estLbrow(2,[1:end 1]), ...
               '-go','LineWidth',lWidth,...
               'MarkerEdgeColor','k',...
               'MarkerFaceColor','w',...
               'MarkerSize',markSize);

   estRbrow = faceCoordinates(:,39:50);
   plot( estRbrow(1,[1:end 1]), estRbrow(2,[1:end 1]), ...
               '-go','LineWidth',lWidth,...
               'MarkerEdgeColor','k',...
               'MarkerFaceColor','w',...
               'MarkerSize',markSize);

   estN = faceCoordinates(:,51:83);
   plot( estN(1,1), estN(2,1), ...
               '-go','LineWidth',lWidth,...
               'MarkerEdgeColor','k',...
               'MarkerFaceColor','w',...
               'MarkerSize',markSize);
   plot( estN(1,2), estN(2,2), ...
               '-go','LineWidth',lWidth,...
               'MarkerEdgeColor','k',...
               'MarkerFaceColor','w',...
               'MarkerSize',markSize);
   plot( estN(1,3:end-4), estN(2,3:end-4), ...
               '-go','LineWidth',lWidth,...
               'MarkerEdgeColor','k',...
               'MarkerFaceColor','w',...
               'MarkerSize',markSize);
   plot( estN(1,end-3:end), estN(2,end-3:end), ...
               '-go','LineWidth',lWidth,...
               'MarkerEdgeColor','k',...
               'MarkerFaceColor','w',...
               'MarkerSize',markSize);

   estM = faceCoordinates(:,84:109);
   plot( estM(1,[ 1:end-6 1 ]), estM(2,[1:end-6 1 ] ), ...
               '-go','LineWidth',lWidth,...
               'MarkerEdgeColor','k',...
               'MarkerFaceColor','w',...
               'MarkerSize',markSize);
    plot( estM(1,[1 21:23 11 (end-2):end 1]), estM(2,[1 21:23 11 ...
                            (end-2):end 1 ]), ...
               '-go','LineWidth',lWidth,...
               'MarkerEdgeColor','k',...
               'MarkerFaceColor','w',...
               'MarkerSize',markSize);

   estC = faceCoordinates(:,110:130);
   plot( estC(1,:), estC(2,:), ...
               '-go','LineWidth',lWidth,...
               'MarkerEdgeColor','k',...
               'MarkerFaceColor','w',...
               'MarkerSize',markSize);

   %following code deals with output range.  
    if ~isempty( small )
       minX = min( faceCoordinates(1,:) );
       maxX = max( faceCoordinates(1,:) );
       minY = min( faceCoordinates(2,:) );
       maxY = max( faceCoordinates(2,:) );

        if small == 1 %20 inter-eye
            axis( [ minX-10 maxX+10 minY-17 maxY+10] );
        elseif small == 2 %10 inter-eye
            axis( [ minX-5 maxX+5 minY-8 maxY+5] );
        elseif small ==3 % 5 interEye
            axis( [ minX-2 maxX+2 minY-4 maxY+2] )
        else
            axis( [ minX-20 maxX+20 minY-35 maxY+20] );
        end

        if small == 1  % 20 inter-eye distance
            rect = [5, 5, 800, 800];
            set(gcf,'Position', rect )
        
        elseif small == 2 %10 inter-eye distance
            rect = [5, 5, 1200, 1200];
            set(gcf,'Position', rect ) 
        elseif small == 3 %5 inter-eye distance
            rect = [5, 5, 2200, 2200];
            set(gcf,'Position', rect ) 
        end
    end    
    
else
    display( 'wrong number face landmarks');
end