function fig = heat_desgn()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.

load heat_desgn

h0 = figure('Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[232 258 560 420], ...
	'ResizeFcn','doresize(gcbf)', ...
	'ToolBar','figure', ...
	'DefaultaxesCreateFcn','plotedit(gcbf,''promoteoverlay''); ');
h1 = uimenu('Parent',h0, ...
	'HandleVisibility','off', ...
	'Tag','ScribeHGBinObject', ...
	'Visible','off');
h1 = uimenu('Parent',h0, ...
	'HandleVisibility','off', ...
	'Tag','ScribeFigObjStorage', ...
	'Visible','off');
h1 = uimenu('Parent',h0, ...
	'HandleVisibility','off', ...
	'Tag','ScribeHGBinObject', ...
	'Visible','off');
h1 = axes('Parent',h0, ...
	'Box','on', ...
	'CameraUpVector',[0 1 0], ...
	'Color',[1 1 1], ...
	'ColorOrder',mat1, ...
	'CreateFcn','plotedit(gcbf,''promoteoverlay''); ', ...
	'FontName','Arial Cyr', ...
	'XColor',[0 0 0], ...
	'XLim',[-0.2 1.2], ...
	'XLimMode','manual', ...
	'YColor',[0 0 0], ...
	'YLim',[-0.2 1.2], ...
	'YLimMode','manual', ...
	'ZColor',[0 0 0]);
h2 = line('Parent',h1, ...
	'Color',[0 0 0], ...
	'LineWidth',3, ...
	'YData',[0.2 0.2]);
h2 = line('Parent',h1, ...
	'Color',[0 0 0], ...
	'LineWidth',3, ...
	'YData',[0.8 0.8]);
h2 = text('Parent',h1, ...
	'ButtonDownFcn','scriberestoresavefcns', ...
	'Color',[0 0 0], ...
	'FontName','Arial Cyr', ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',mat2, ...
	'String',mat3, ...
	'VerticalAlignment','bottom');
set(get(h2,'Parent'),'Title',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[0.4983833718244803 -0.2985337243401761 17.32050807568877], ...
	'VerticalAlignment','cap');
set(get(h2,'Parent'),'XLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[-0.3163972286374134 0.493841642228739 17.32050807568877], ...
	'Rotation',90, ...
	'VerticalAlignment','baseline');
set(get(h2,'Parent'),'YLabel',h2);
h1 = uicontextmenu('Parent',h0, ...
	'Callback','domymenu update', ...
	'HandleVisibility','off', ...
	'Tag','ScribeEditlineObjContextMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu cut', ...
	'HandleVisibility','off', ...
	'Label','Cu&t', ...
	'Tag','ScribeEditlineObjCutMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu copy', ...
	'HandleVisibility','off', ...
	'Label','&Copy', ...
	'Tag','ScribeEditlineObjCopyMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu paste', ...
	'HandleVisibility','off', ...
	'Label','&Paste', ...
	'Tag','ScribeEditlineObjPasteMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu clear', ...
	'HandleVisibility','off', ...
	'Label','Clea&r', ...
	'Tag','ScribeEditlineObjClearMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu size', ...
	'HandleVisibility','off', ...
	'Label','Line &Width', ...
	'Separator','on', ...
	'Tag','ScribeEditlineObjSizeMenu');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 0.5', ...
	'HandleVisibility','off', ...
	'Label','0.5', ...
	'Tag','ScribeEditlineObjSizeMenu0.5');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 1', ...
	'HandleVisibility','off', ...
	'Label','1', ...
	'Tag','ScribeEditlineObjSizeMenu1');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 2', ...
	'HandleVisibility','off', ...
	'Label','2', ...
	'Tag','ScribeEditlineObjSizeMenu2');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 3', ...
	'HandleVisibility','off', ...
	'Label','3', ...
	'Tag','ScribeEditlineObjSizeMenu3');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 4', ...
	'HandleVisibility','off', ...
	'Label','4', ...
	'Tag','ScribeEditlineObjSizeMenu4');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 5', ...
	'HandleVisibility','off', ...
	'Label','5', ...
	'Tag','ScribeEditlineObjSizeMenu5');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 6', ...
	'HandleVisibility','off', ...
	'Label','6', ...
	'Tag','ScribeEditlineObjSizeMenu6');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 7', ...
	'HandleVisibility','off', ...
	'Label','7', ...
	'Tag','ScribeEditlineObjSizeMenu7');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 8', ...
	'HandleVisibility','off', ...
	'Label','8', ...
	'Tag','ScribeEditlineObjSizeMenu8');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 9', ...
	'HandleVisibility','off', ...
	'Label','9', ...
	'Tag','ScribeEditlineObjSizeMenu9');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 10', ...
	'HandleVisibility','off', ...
	'Label','10', ...
	'Tag','ScribeEditlineObjSizeMenu10');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu more', ...
	'HandleVisibility','off', ...
	'Label','more...', ...
	'Tag','ScribeEditlineObjSizeMenuMore');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu style', ...
	'HandleVisibility','off', ...
	'Label','Line &Style', ...
	'Tag','ScribeEditlineObjStyleMenu');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu style solid', ...
	'HandleVisibility','off', ...
	'Label','solid', ...
	'Tag','ScribeEditlineObjStyleMenuSolid');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu style dash', ...
	'HandleVisibility','off', ...
	'Label','dash', ...
	'Tag','ScribeEditlineObjStyleMenuDash');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu style dot', ...
	'HandleVisibility','off', ...
	'Label','dot', ...
	'Tag','ScribeEditlineObjStyleMenuDot');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu style dashdot', ...
	'HandleVisibility','off', ...
	'Label','dash-dot', ...
	'Tag','ScribeEditlineObjStyleMenuDashDot');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu color', ...
	'HandleVisibility','off', ...
	'Label','Color...', ...
	'Tag','ScribeEditlineObjColorMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu more', ...
	'HandleVisibility','off', ...
	'Label','Properties...', ...
	'Separator','on', ...
	'Tag','ScribeEditlineObjMoreMenu');
h1 = uicontextmenu('Parent',h0, ...
	'Callback','domymenu update', ...
	'HandleVisibility','off', ...
	'Tag','ScribeAxisObjContextMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu cut', ...
	'HandleVisibility','off', ...
	'Label','Cu&t', ...
	'Tag','ScribeAxisObjCutMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu copy', ...
	'HandleVisibility','off', ...
	'Label','&Copy', ...
	'Tag','ScribeAxisObjCopyMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu paste', ...
	'HandleVisibility','off', ...
	'Label','&Paste', ...
	'Tag','ScribeAxisObjPasteMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu clear', ...
	'HandleVisibility','off', ...
	'Label','Clea&r', ...
	'Tag','ScribeAxisObjClearMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu showlegend', ...
	'HandleVisibility','off', ...
	'Label','Show Legend', ...
	'Separator','on', ...
	'Tag','ScribeAxisObjShowLegendMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu moveresize', ...
	'HandleVisibility','off', ...
	'Label','Lock Position', ...
	'Separator','on', ...
	'Tag','ScribeAxisObjMoveResizeMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu more', ...
	'HandleVisibility','off', ...
	'Label','Properties...', ...
	'Separator','on', ...
	'Tag','ScribeAxischildObjMoreMenu');
h1 = uicontextmenu('Parent',h0, ...
	'Callback','domymenu update', ...
	'HandleVisibility','off', ...
	'Tag','ScribeAxistextObjContextMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu cut', ...
	'HandleVisibility','off', ...
	'Label','Cu&t', ...
	'Tag','ScribeAxistextObjCutMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu copy', ...
	'HandleVisibility','off', ...
	'Label','&Copy', ...
	'Tag','ScribeAxistextObjCopyMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu paste', ...
	'Enable','off', ...
	'HandleVisibility','off', ...
	'Label','&Paste', ...
	'Tag','ScribeAxistextObjPasteMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu clear', ...
	'HandleVisibility','off', ...
	'Label','Clea&r', ...
	'Tag','ScribeAxistextObjClearMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu string', ...
	'HandleVisibility','off', ...
	'Label','&String...', ...
	'Separator','on', ...
	'Tag','ScribeAxistextObjStringMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu size', ...
	'HandleVisibility','off', ...
	'Label','&Font Size', ...
	'Tag','ScribeAxistextObjSizeMenu');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 4', ...
	'HandleVisibility','off', ...
	'Label','4', ...
	'Tag','ScribeEditlineObjSizeMenu4');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 6', ...
	'HandleVisibility','off', ...
	'Label','6', ...
	'Tag','ScribeEditlineObjSizeMenu6');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 8', ...
	'HandleVisibility','off', ...
	'Label','8', ...
	'Tag','ScribeEditlineObjSizeMenu8');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 9', ...
	'HandleVisibility','off', ...
	'Label','9', ...
	'Tag','ScribeEditlineObjSizeMenu9');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 10', ...
	'Checked','on', ...
	'HandleVisibility','off', ...
	'Label','10', ...
	'Tag','ScribeEditlineObjSizeMenu10');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 11', ...
	'HandleVisibility','off', ...
	'Label','11', ...
	'Tag','ScribeEditlineObjSizeMenu11');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 12', ...
	'HandleVisibility','off', ...
	'Label','12', ...
	'Tag','ScribeEditlineObjSizeMenu12');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 14', ...
	'HandleVisibility','off', ...
	'Label','14', ...
	'Tag','ScribeEditlineObjSizeMenu14');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 18', ...
	'HandleVisibility','off', ...
	'Label','18', ...
	'Tag','ScribeEditlineObjSizeMenu18');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 24', ...
	'HandleVisibility','off', ...
	'Label','24', ...
	'Tag','ScribeEditlineObjSizeMenu24');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 32', ...
	'HandleVisibility','off', ...
	'Label','32', ...
	'Tag','ScribeEditlineObjSizeMenu32');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu font', ...
	'HandleVisibility','off', ...
	'Label','more...', ...
	'Tag','ScribeEditlineObjSizeMenuMore');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu style', ...
	'HandleVisibility','off', ...
	'Label','Font St&yle', ...
	'Tag','ScribeAxistextObjStyleMenu');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu style normal', ...
	'Checked','on', ...
	'HandleVisibility','off', ...
	'Label','&Normal', ...
	'Tag','ScribeAxistextObjStyleMenuNormal');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu style italic', ...
	'HandleVisibility','off', ...
	'Label','&Italic', ...
	'Tag','ScribeAxistextdObjStyleMenuItalic');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu style bold', ...
	'HandleVisibility','off', ...
	'Label','&Bold', ...
	'Tag','ScribeAxistextObjStyleMenuBold');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu color', ...
	'HandleVisibility','off', ...
	'Label','Co&lor...', ...
	'Tag','ScribeAxistextObjColorMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu font', ...
	'HandleVisibility','off', ...
	'Label','&Properties...', ...
	'Separator','on', ...
	'Tag','ScribeAxistextObjMoreMenu');
h1 = axes('Parent',h0, ...
	'CameraUpVector',[0 1 0], ...
	'Color','none', ...
	'ColorOrder',mat4, ...
	'CreateFcn','', ...
	'HandleVisibility','off', ...
	'HitTest','off', ...
	'Position',[0 0 1 1], ...
	'Tag','ScribeOverlayAxesActive', ...
	'Visible','off', ...
	'XColor',[0.8 0.8 0.8], ...
	'XLimMode','manual', ...
	'XTickMode','manual', ...
	'YColor',[0.8 0.8 0.8], ...
	'YLimMode','manual', ...
	'YTickMode','manual', ...
	'ZColor',[0 0 0]);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'FontName','Arial Cyr', ...
	'Position',[0.4625000000000002 0.2571428571428571 0], ...
	'String','Изделие ');
h2 = text('Parent',h1, ...
	'Color',[0.8 0.8 0.8], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[0.4991055456171735 -0.01909307875895006 17.32050807568877], ...
	'VerticalAlignment','cap', ...
	'Visible','off');
set(get(h2,'Parent'),'XLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0.8 0.8 0.8], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[-0.01252236135957066 0.4964200477326969 17.32050807568877], ...
	'Rotation',90, ...
	'VerticalAlignment','baseline', ...
	'Visible','off');
set(get(h2,'Parent'),'YLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','right', ...
	'Position',[-0.001788908765652952 0.9976133651551312 17.32050807568877], ...
	'Visible','off');
set(get(h2,'Parent'),'ZLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',mat5, ...
	'VerticalAlignment','bottom', ...
	'Visible','off');
set(get(h2,'Parent'),'Title',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'FontName','Arial Cyr', ...
	'Position',[0.4357142857142857 0.7380952380952381 0], ...
	'String','Нагреватель ');
h2 = line('Parent',h1, ...
	'ButtonDownFcn','scriberestoresavefcns', ...
	'Color',[0 0 0], ...
	'LineStyle','none', ...
	'Tag','ScribeArrowlineObject', ...
	'UserData','1.440009e+002', ...
	'XData',[0.6821428571428571 0.6821428571428571], ...
	'YData',[0.4785714285714285 0.3476190476190477]);
h2 = line('Parent',h1, ...
	'Color',[0 0 0], ...
	'Tag','ScribeArrowlineBody', ...
	'UserData','1.440009e+002', ...
	'XData',[0.6821428571428571 0.6821428571428571], ...
	'YData',[0.4785714285714285 0.3666666666666668]);
h2 = patch('Parent',h1, ...
	'FaceColor',[0 0 0], ...
	'Faces',[1 2 3 4 5], ...
	'Tag','ScribeArrowlineHead', ...
	'UserData','1.440009e+002', ...
	'VertexNormals',mat6, ...
	'Vertices',mat7);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'Position',[0.6767857142857142 0.5190476190476188 0], ...
	'String','H ');
h2 = line('Parent',h1, ...
	'Color',[0 0 0], ...
	'XData',[0.2410714285714286 0.2410714285714286], ...
	'YData',[0.3357142857142857 0.2952380952380952]);
h2 = line('Parent',h1, ...
	'Color',[0 0 0], ...
	'XData',[0.7892857142857144 0.7892857142857144], ...
	'YData',[0.3357142857142857 0.2904761904761906]);
h2 = line('Parent',h1, ...
	'ButtonDownFcn','scriberestoresavefcns', ...
	'Color',[0 0 0], ...
	'LineStyle','none', ...
	'Tag','ScribeArrowlineObject', ...
	'UserData','1.530009e+002', ...
	'XData',mat8, ...
	'YData',[0.3095238095238092 0.3095238095238094]);
h2 = line('Parent',h1, ...
	'Color',[0 0 0], ...
	'Tag','ScribeArrowlineBody', ...
	'UserData','1.530009e+002', ...
	'XData',[0.4857142857142856 0.2571428571428571], ...
	'YData',[0.3095238095238092 0.3095238095238094]);
h2 = patch('Parent',h1, ...
	'FaceColor',[0 0 0], ...
	'Faces',[1 2 3 4 5], ...
	'Tag','ScribeArrowlineHead', ...
	'UserData','1.530009e+002', ...
	'VertexNormals',mat9, ...
	'Vertices',mat10);
h2 = line('Parent',h1, ...
	'Color',[0 0 0], ...
	'LineStyle','none', ...
	'Tag','ScribeArrowlineObject', ...
	'UserData','1.560009e+002', ...
	'XData',[0.555357142857143 0.7875000000000001], ...
	'YData',[0.3095238095238094 0.3095238095238094]);
h2 = line('Parent',h1, ...
	'Color',[0 0 0], ...
	'Tag','ScribeArrowlineBody', ...
	'UserData','1.560009e+002', ...
	'XData',[0.555357142857143 0.7732142857142859], ...
	'YData',[0.3095238095238094 0.3095238095238094]);
h2 = patch('Parent',h1, ...
	'FaceColor',[0 0 0], ...
	'Faces',[1 2 3 4 5], ...
	'Tag','ScribeArrowlineHead', ...
	'UserData','1.560009e+002', ...
	'VertexNormals',mat11, ...
	'Vertices',mat12);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'Position',[0.5196428571428571 0.3095238095238095 0], ...
	'String','L ');
h2 = line('Parent',h1, ...
	'Color',[0 0 0], ...
	'LineStyle','none', ...
	'Tag','ScribeArrowlineObject', ...
	'UserData','1.480010e+002', ...
	'XData',[0.6803571428571429 0.6803571428571429], ...
	'YData',[0.5571428571428571 0.6857142857142857]);
h2 = line('Parent',h1, ...
	'Color',[0 0 0], ...
	'Tag','ScribeArrowlineBody', ...
	'UserData','1.480010e+002', ...
	'XData',[0.6803571428571429 0.6803571428571429], ...
	'YData',[0.5571428571428571 0.6666666666666666]);
h2 = patch('Parent',h1, ...
	'FaceColor',[0 0 0], ...
	'Faces',[1 2 3 4 5], ...
	'Tag','ScribeArrowlineHead', ...
	'UserData','1.480010e+002', ...
	'VertexNormals',mat13, ...
	'Vertices',mat14);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'Position',[0.35 0.5238095238095238 0], ...
	'String','\gamma=H/L ');
if nargout > 0, fig = h0; end
