function [cam_mats] = fun_ReadCamVecFromFile(FilePath, ...
    CamInfo, ...
    total_frame_num)
% Read camera image and reshape to vecs

    cam_mats = cell(total_frame_num,1);
    for frm_idx = 1:total_frame_num
        tmp_img = double(imread([FilePath.main_file_path, ...
            FilePath.img_file_path, ...
            FilePath.img_file_name, ...
            num2str(frm_idx), ...
            FilePath.img_file_suffix]));
        range_img = tmp_img(CamInfo.range_mat(2,1):CamInfo.range_mat(2,2), ...
            CamInfo.range_mat(1,1):CamInfo.range_mat(1,2));
        cam_mats{frm_idx,1} = range_img;
    end

end
